<?php

namespace Database\Seeders;

use App\Models\League;
use Illuminate\Database\Seeder;

class LeagueTableContentSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['slug' => 'premier-league', 'table_intro' => 'One matchday in, Liverpool sit top of the Premier League on goal difference from Everton, with Manchester City, Sunderland, Brighton, Manchester United and Wolves all level on points after opening wins of their own. The table below reflects nothing more than a single result apiece for every club &mdash; treat it as an early snapshot, not a verdict &mdash; but it\'s already worth a look at who\'s making the fastest start.', 'table_closing' => 'What stands out most after one round is how evenly points are currently spread: seven clubs already have maximum points, and only goal difference currently separates Liverpool from a genuine pack of contenders behind them. Newly promoted Sunderland sitting inside the Champions League places, however briefly, is the kind of small early shock that always draws attention in the opening weeks of a season, even if nobody seriously expects it to last. At the bottom, Chelsea, Fulham, Leeds United and Tottenham make up an early bottom four that includes some familiar names and one eyebrow-raising one in Tottenham, who spent last season chasing European qualification. A single round of fixtures rarely tells the full story, but the standings will sharpen quickly as the season\'s real form lines begin to emerge over the coming weeks.'],
            ['slug' => 'la-liga', 'table_intro' => 'Barcelona lead the way after Matchday 1 on goal difference, ahead of Real Madrid, Athletic Bilbao and Espanyol, with four more clubs level on three points after opening wins. As in every league, one round of results settles very little &mdash; but it\'s the first real data point of a long season, and worth a look.', 'table_closing' => 'The presence of Girona, Leganes and Osasuna inside the early top seven is a reminder of how competitive the middle of La Liga has become in recent seasons, even as Real Madrid and Barcelona remain the clear financial and historical heavyweights at the top. Atl&eacute;tico Madrid sitting mid-table after one round is unlikely to cause genuine alarm at the Metropolitano, but it\'s a reminder that Diego Simeone\'s sides have rarely started fast. At the bottom, Real Sociedad and Valencia\'s heavy opening defeats have them occupying relegation-zone positions earlier than either club would like, while Villarreal and newly promoted Valladolid round out an early bottom four. It\'s the smallest of sample sizes, but La Liga\'s traditional shape &mdash; Real Madrid and Barcelona at the top, a fiercely contested middle, and a handful of clubs fighting from matchday one to stay up &mdash; already looks familiar.'],
            ['slug' => 'serie-a', 'table_intro' => 'Atalanta head the Serie A table after Matchday 1 on goal difference from Inter Milan, with Como, AC Milan, Sassuolo, Bologna and Lecce all level on maximum points after opening wins of their own. As ever with a single round of results, treat the early shape of the table as a snapshot rather than a forecast.', 'table_closing' => 'Como\'s position inside the current top three, alongside fellow surprise packages Sassuolo, Bologna and Lecce, is an early reminder of how unpredictable an opening round can be &mdash; none of the four are traditional title contenders, but all four made the most of their first fixture. Napoli and Juventus sharing a point in their opening meeting was a fair reflection of two evenly matched sides still finding their rhythm under newer head coaches. At the other end, Parma, Torino, Udinese and Venezia make up an early bottom four, with Fiorentina and Genoa also winless after round one. Serie A\'s title race has, in recent seasons, regularly come down to fine margins between Inter, Napoli and whichever challenger has its best campaign &mdash; round one alone won\'t decide who that is this time, but every club will already be watching the table closely.'],
            ['slug' => 'bundesliga', 'table_intro' => 'Bayern Munich lead the Bundesliga after Matchday 1 on goal difference from Borussia Dortmund, with newly promoted Heidenheim occupying an early Champions League place alongside Mainz and Eintracht Frankfurt. A single round rarely means much on its own, but it\'s the first marker of a long campaign.', 'table_closing' => 'Heidenheim\'s position in the early top three, sitting above Bayer Leverkusen and reigning title challengers RB Leipzig, is exactly the kind of opening-weekend anomaly that makes round one worth watching even though it won\'t last &mdash; a club with the smallest budget and stadium in the division briefly outranking some of German football\'s best-resourced sides. Leverkusen\'s draw leaves Kasper Hjulmand\'s first Bundesliga table entry as Bayer\'s head coach a modest one, a reminder of how much the club must replace after Xabi Alonso\'s unbeaten title-winning season. At the bottom, RB Leipzig, Union Berlin, Werder Bremen and Wolfsburg make up an early bottom four that few would have predicted before a ball was kicked, particularly Leipzig given their usual position among the division\'s Champions League regulars. Bayern\'s position at the summit, though, will surprise nobody &mdash; the champions have now started the title defence exactly as they intended to.'],
            ['slug' => 'ligue-1', 'table_intro' => 'Paris Saint-Germain sit top of Ligue 1 after Matchday 1 on goal difference, with Brest and Rennes both level on points and goal difference just behind the champions, and Marseille, Le Havre and Lens rounding out an early perfect-record group. It\'s the smallest possible sample size, but every club\'s season now has its first data point.', 'table_closing' => 'Brest and Rennes occupying places directly behind PSG is a fitting early continuation of both clubs\' recent European progress, while Marseille\'s win under new head coach Roberto De Zerbi will be seen at the V&eacute;lodrome as an encouraging first sign after a difficult few seasons of boardroom turbulence. Monaco\'s position in the bottom half after one round is unlikely to cause real concern this early, but it\'s a quieter start than Adi H&uuml;tter\'s side would have wanted. At the bottom, Nantes, Nice and Strasbourg make up an early bottom three alongside a winless Montpellier, four clubs that will already be aware of how quickly Ligue 1\'s lower half can turn into a genuine relegation fight. PSG\'s position at the summit is, as in recent seasons, the least surprising story of the round &mdash; the real question all year will be which club, if any, can consistently live with them.'],
        ];

        foreach ($rows as $row) {
            League::where('slug', $row['slug'])->update([
                'table_intro' => $row['table_intro'],
                'table_closing' => $row['table_closing'],
            ]);
        }
    }
}
