<?php

namespace Database\Seeders;

use App\Models\League;
use App\Models\Team;
use Illuminate\Database\Seeder;

class TeamSeeder extends Seeder
{
    public function run(): void
    {
        $teams = [
            ['league_slug' => 'bundesliga', 'name' => 'Heidenheim', 'full_name' => '1. FC Heidenheim 1846', 'slug' => '1-fc-heidenheim', 'crest_code' => 'fch', 'color_hex' => '#E2001A', 'stadium' => 'Voith-Arena', 'stadium_capacity' => '15,000', 'manager' => 'Frank Schmidt', 'founded_year' => 1846],
            ['league_slug' => 'serie-a', 'name' => 'AC Milan', 'full_name' => 'AC Milan', 'slug' => 'ac-milan', 'crest_code' => 'mil', 'color_hex' => '#FB090B', 'stadium' => 'Giuseppe Meazza (San Siro)', 'stadium_capacity' => '80,018', 'manager' => 'Massimiliano Allegri', 'founded_year' => 1899],
            ['league_slug' => 'premier-league', 'name' => 'Bournemouth', 'full_name' => 'AFC Bournemouth', 'slug' => 'afc-bournemouth', 'crest_code' => 'bou', 'color_hex' => '#DA020E', 'stadium' => 'Vitality Stadium', 'stadium_capacity' => '11,307', 'manager' => 'Andoni Iraola', 'founded_year' => 1899],
            ['league_slug' => 'ligue-1', 'name' => 'Auxerre', 'full_name' => 'AJ Auxerre', 'slug' => 'aj-auxerre', 'crest_code' => 'aja', 'color_hex' => '#003DA5', 'stadium' => 'Stade de l\'Abbe-Deschamps', 'stadium_capacity' => '23,467', 'manager' => 'Christophe Pelissier', 'founded_year' => 1905],
            ['league_slug' => 'ligue-1', 'name' => 'Angers', 'full_name' => 'Angers SCO', 'slug' => 'angers-sco', 'crest_code' => 'ang', 'color_hex' => '#000000', 'stadium' => 'Stade Raymond-Kopa', 'stadium_capacity' => '18,752', 'manager' => 'Alexandre Dujeux', 'founded_year' => 1919],
            ['league_slug' => 'premier-league', 'name' => 'Arsenal', 'full_name' => 'Arsenal FC', 'slug' => 'arsenal', 'crest_code' => 'ars', 'color_hex' => '#EF0107', 'stadium' => 'Emirates Stadium', 'stadium_capacity' => '60,704', 'manager' => 'Mikel Arteta', 'founded_year' => 1886],
            ['league_slug' => 'ligue-1', 'name' => 'Monaco', 'full_name' => 'AS Monaco FC', 'slug' => 'as-monaco', 'crest_code' => 'asm', 'color_hex' => '#ED1C24', 'stadium' => 'Stade Louis II', 'stadium_capacity' => '18,523', 'manager' => 'Adi Hutter', 'founded_year' => 1924],
            ['league_slug' => 'serie-a', 'name' => 'Roma', 'full_name' => 'AS Roma', 'slug' => 'as-roma', 'crest_code' => 'rom', 'color_hex' => '#8E1F2F', 'stadium' => 'Stadio Olimpico', 'stadium_capacity' => '70,634', 'manager' => 'Gian Piero Gasperini', 'founded_year' => 1927],
            ['league_slug' => 'premier-league', 'name' => 'Aston Villa', 'full_name' => 'Aston Villa FC', 'slug' => 'aston-villa', 'crest_code' => 'avl', 'color_hex' => '#95101B', 'stadium' => 'Villa Park', 'stadium_capacity' => '42,682', 'manager' => 'Unai Emery', 'founded_year' => 1874],
            ['league_slug' => 'serie-a', 'name' => 'Atalanta', 'full_name' => 'Atalanta BC', 'slug' => 'atalanta', 'crest_code' => 'ata', 'color_hex' => '#1D3557', 'stadium' => 'Gewiss Stadium', 'stadium_capacity' => '21,300', 'manager' => 'Ivan Juric', 'founded_year' => 1907],
            ['league_slug' => 'la-liga', 'name' => 'Athletic Bilbao', 'full_name' => 'Athletic Club Bilbao', 'slug' => 'athletic-bilbao', 'crest_code' => 'ath', 'color_hex' => '#EE2523', 'stadium' => 'San Mames', 'stadium_capacity' => '53,289', 'manager' => 'Ernesto Valverde', 'founded_year' => 1898],
            ['league_slug' => 'la-liga', 'name' => 'Atletico Madrid', 'full_name' => 'Club Atletico de Madrid', 'slug' => 'atletico-madrid', 'crest_code' => 'atm', 'color_hex' => '#CB3524', 'stadium' => 'Civitas Metropolitano', 'stadium_capacity' => '70,460', 'manager' => 'Diego Simeone', 'founded_year' => 1903],
            ['league_slug' => 'la-liga', 'name' => 'Barcelona', 'full_name' => 'FC Barcelona', 'slug' => 'barcelona', 'crest_code' => 'bar', 'color_hex' => '#A50044', 'stadium' => 'Estadi Olimpic Lluis Companys', 'stadium_capacity' => '55,926', 'manager' => 'Hansi Flick', 'founded_year' => 1899],
            ['league_slug' => 'bundesliga', 'name' => 'Bayer Leverkusen', 'full_name' => 'Bayer 04 Leverkusen', 'slug' => 'bayer-leverkusen', 'crest_code' => 'b04', 'color_hex' => '#E32221', 'stadium' => 'BayArena', 'stadium_capacity' => '30,210', 'manager' => 'Kasper Hjulmand', 'founded_year' => 1904],
            ['league_slug' => 'bundesliga', 'name' => 'Bayern Munich', 'full_name' => 'FC Bayern Munich', 'slug' => 'bayern-munich', 'crest_code' => 'bay', 'color_hex' => '#DC052D', 'stadium' => 'Allianz Arena', 'stadium_capacity' => '75,000', 'manager' => 'Vincent Kompany', 'founded_year' => 1900],
            ['league_slug' => 'serie-a', 'name' => 'Bologna', 'full_name' => 'Bologna FC 1909', 'slug' => 'bologna', 'crest_code' => 'bol', 'color_hex' => '#A6192E', 'stadium' => 'Stadio Renato Dall\'Ara', 'stadium_capacity' => '36,462', 'manager' => 'Vincenzo Italiano', 'founded_year' => 1909],
            ['league_slug' => 'bundesliga', 'name' => 'Borussia Dortmund', 'full_name' => 'Borussia Dortmund', 'slug' => 'borussia-dortmund', 'crest_code' => 'bvb', 'color_hex' => '#FDE100', 'stadium' => 'Signal Iduna Park', 'stadium_capacity' => '81,365', 'manager' => 'Niko Kovac', 'founded_year' => 1909],
            ['league_slug' => 'bundesliga', 'name' => 'Mönchengladbach', 'full_name' => 'Borussia Monchengladbach', 'slug' => 'borussia-monchengladbach', 'crest_code' => 'bmg', 'color_hex' => '#00A650', 'stadium' => 'Borussia-Park', 'stadium_capacity' => '54,057', 'manager' => 'Gerardo Seoane', 'founded_year' => 1900],
            ['league_slug' => 'premier-league', 'name' => 'Brentford', 'full_name' => 'Brentford FC', 'slug' => 'brentford', 'crest_code' => 'bre', 'color_hex' => '#E30613', 'stadium' => 'Gtech Community Stadium', 'stadium_capacity' => '17,250', 'manager' => 'Keith Andrews', 'founded_year' => 1889],
            ['league_slug' => 'premier-league', 'name' => 'Brighton', 'full_name' => 'Brighton & Hove Albion FC', 'slug' => 'brighton-hove-albion', 'crest_code' => 'bha', 'color_hex' => '#0057B8', 'stadium' => 'Amex Stadium', 'stadium_capacity' => '31,800', 'manager' => 'Fabian Hurzeler', 'founded_year' => 1901],
            ['league_slug' => 'premier-league', 'name' => 'Burnley', 'full_name' => 'Burnley FC', 'slug' => 'burnley', 'crest_code' => 'bur', 'color_hex' => '#6C1D45', 'stadium' => 'Turf Moor', 'stadium_capacity' => '21,944', 'manager' => 'Scott Parker', 'founded_year' => 1882],
            ['league_slug' => 'serie-a', 'name' => 'Cagliari', 'full_name' => 'Cagliari Calcio', 'slug' => 'cagliari', 'crest_code' => 'cag', 'color_hex' => '#C8102E', 'stadium' => 'Unipol Domus', 'stadium_capacity' => '16,416', 'manager' => 'Fabio Pisacane', 'founded_year' => 1920],
            ['league_slug' => 'la-liga', 'name' => 'Celta Vigo', 'full_name' => 'RC Celta de Vigo', 'slug' => 'celta-vigo', 'crest_code' => 'cel', 'color_hex' => '#8AC3EE', 'stadium' => 'Estadio Abanca-Balaidos', 'stadium_capacity' => '29,000', 'manager' => 'Claudio Giraldez', 'founded_year' => 1923],
            ['league_slug' => 'premier-league', 'name' => 'Chelsea', 'full_name' => 'Chelsea FC', 'slug' => 'chelsea', 'crest_code' => 'che', 'color_hex' => '#034694', 'stadium' => 'Stamford Bridge', 'stadium_capacity' => '40,343', 'manager' => 'Enzo Maresca', 'founded_year' => 1905],
            ['league_slug' => 'serie-a', 'name' => 'Como', 'full_name' => 'Como 1907', 'slug' => 'como-1907', 'crest_code' => 'com', 'color_hex' => '#004C97', 'stadium' => 'Stadio Giuseppe Sinigaglia', 'stadium_capacity' => '13,602', 'manager' => 'Cesc Fabregas', 'founded_year' => 1907],
            ['league_slug' => 'premier-league', 'name' => 'Crystal Palace', 'full_name' => 'Crystal Palace FC', 'slug' => 'crystal-palace', 'crest_code' => 'cry', 'color_hex' => '#1B458F', 'stadium' => 'Selhurst Park', 'stadium_capacity' => '25,486', 'manager' => 'Oliver Glasner', 'founded_year' => 1905],
            ['league_slug' => 'la-liga', 'name' => 'Alaves', 'full_name' => 'Deportivo Alaves', 'slug' => 'deportivo-alaves', 'crest_code' => 'ala', 'color_hex' => '#0055A4', 'stadium' => 'Mendizorroza', 'stadium_capacity' => '19,840', 'manager' => 'Eduardo Coudet', 'founded_year' => 1921],
            ['league_slug' => 'bundesliga', 'name' => 'Eintracht Frankfurt', 'full_name' => 'Eintracht Frankfurt', 'slug' => 'eintracht-frankfurt', 'crest_code' => 'sge', 'color_hex' => '#E1000F', 'stadium' => 'Deutsche Bank Park', 'stadium_capacity' => '58,000', 'manager' => 'Dino Toppmoller', 'founded_year' => 1899],
            ['league_slug' => 'serie-a', 'name' => 'Empoli', 'full_name' => 'Empoli FC', 'slug' => 'empoli', 'crest_code' => 'emp', 'color_hex' => '#1560BD', 'stadium' => 'Stadio Carlo Castellani', 'stadium_capacity' => '16,284', 'manager' => 'Roberto D\'Aversa', 'founded_year' => 1920],
            ['league_slug' => 'la-liga', 'name' => 'Espanyol', 'full_name' => 'RCD Espanyol de Barcelona', 'slug' => 'espanyol', 'crest_code' => 'esp', 'color_hex' => '#0A4595', 'stadium' => 'RCDE Stadium', 'stadium_capacity' => '40,500', 'manager' => 'Manolo Gonzalez', 'founded_year' => 1900],
            ['league_slug' => 'premier-league', 'name' => 'Everton', 'full_name' => 'Everton FC', 'slug' => 'everton', 'crest_code' => 'eve', 'color_hex' => '#003399', 'stadium' => 'Hill Dickinson Stadium', 'stadium_capacity' => '52,888', 'manager' => 'David Moyes', 'founded_year' => 1878],
            ['league_slug' => 'bundesliga', 'name' => 'Augsburg', 'full_name' => 'FC Augsburg', 'slug' => 'fc-augsburg', 'crest_code' => 'fca', 'color_hex' => '#BA3733', 'stadium' => 'WWK Arena', 'stadium_capacity' => '30,660', 'manager' => 'Jess Thorup', 'founded_year' => 1907],
            ['league_slug' => 'ligue-1', 'name' => 'Metz', 'full_name' => 'Football Club de Metz', 'slug' => 'fc-metz', 'crest_code' => 'met', 'color_hex' => '#7B0323', 'stadium' => 'Stade Saint-Symphorien', 'stadium_capacity' => '25,976', 'manager' => 'Sead Ramovic', 'founded_year' => 1932],
            ['league_slug' => 'ligue-1', 'name' => 'Nantes', 'full_name' => 'FC Nantes', 'slug' => 'fc-nantes', 'crest_code' => 'nan', 'color_hex' => '#FFD700', 'stadium' => 'Stade de la Beaujoire', 'stadium_capacity' => '35,322', 'manager' => 'Luis Castro', 'founded_year' => 1943],
            ['league_slug' => 'bundesliga', 'name' => 'St. Pauli', 'full_name' => 'FC St. Pauli', 'slug' => 'fc-st-pauli', 'crest_code' => 'stp', 'color_hex' => '#8B4513', 'stadium' => 'Millerntor-Stadion', 'stadium_capacity' => '29,546', 'manager' => 'Alexander Blessin', 'founded_year' => 1910],
            ['league_slug' => 'serie-a', 'name' => 'Fiorentina', 'full_name' => 'ACF Fiorentina', 'slug' => 'fiorentina', 'crest_code' => 'fio', 'color_hex' => '#6E2585', 'stadium' => 'Stadio Artemio Franchi', 'stadium_capacity' => '43,147', 'manager' => 'Raffaele Palladino', 'founded_year' => 1926],
            ['league_slug' => 'premier-league', 'name' => 'Fulham', 'full_name' => 'Fulham FC', 'slug' => 'fulham', 'crest_code' => 'ful', 'color_hex' => '#000000', 'stadium' => 'Craven Cottage', 'stadium_capacity' => '29,700', 'manager' => 'Marco Silva', 'founded_year' => 1879],
            ['league_slug' => 'serie-a', 'name' => 'Genoa', 'full_name' => 'Genoa CFC', 'slug' => 'genoa', 'crest_code' => 'gen', 'color_hex' => '#C41230', 'stadium' => 'Stadio Luigi Ferraris', 'stadium_capacity' => '36,599', 'manager' => 'Patrick Vieira', 'founded_year' => 1893],
            ['league_slug' => 'la-liga', 'name' => 'Getafe', 'full_name' => 'Getafe CF', 'slug' => 'getafe', 'crest_code' => 'get', 'color_hex' => '#005999', 'stadium' => 'Coliseum Alfonso Perez', 'stadium_capacity' => '17,393', 'manager' => 'Jose Bordalas', 'founded_year' => 1946],
            ['league_slug' => 'la-liga', 'name' => 'Girona', 'full_name' => 'Girona FC', 'slug' => 'girona', 'crest_code' => 'gir', 'color_hex' => '#CC0000', 'stadium' => 'Estadi Montilivi', 'stadium_capacity' => '14,624', 'manager' => 'Michel Sanchez', 'founded_year' => 1930],
            ['league_slug' => 'serie-a', 'name' => 'Verona', 'full_name' => 'Hellas Verona FC', 'slug' => 'hellas-verona', 'crest_code' => 'ver', 'color_hex' => '#FFD700', 'stadium' => 'Stadio Marcantonio Bentegodi', 'stadium_capacity' => '31,045', 'manager' => 'Paolo Zanetti', 'founded_year' => 1903],
            ['league_slug' => 'bundesliga', 'name' => 'Holstein Kiel', 'full_name' => 'Holstein Kiel', 'slug' => 'holstein-kiel', 'crest_code' => 'kie', 'color_hex' => '#003DA5', 'stadium' => 'Holstein-Stadion', 'stadium_capacity' => '15,034', 'manager' => 'Marcel Rapp', 'founded_year' => 1900],
            ['league_slug' => 'serie-a', 'name' => 'Inter Milan', 'full_name' => 'FC Internazionale Milano', 'slug' => 'inter-milan', 'crest_code' => 'int', 'color_hex' => '#010E80', 'stadium' => 'Giuseppe Meazza (San Siro)', 'stadium_capacity' => '80,018', 'manager' => 'Cristian Chivu', 'founded_year' => 1908],
            ['league_slug' => 'serie-a', 'name' => 'Juventus', 'full_name' => 'Juventus FC', 'slug' => 'juventus', 'crest_code' => 'juv', 'color_hex' => '#000000', 'stadium' => 'Allianz Stadium', 'stadium_capacity' => '41,507', 'manager' => 'Igor Tudor', 'founded_year' => 1897],
            ['league_slug' => 'la-liga', 'name' => 'Las Palmas', 'full_name' => 'UD Las Palmas', 'slug' => 'las-palmas', 'crest_code' => 'lpa', 'color_hex' => '#FFE500', 'stadium' => 'Estadio Gran Canaria', 'stadium_capacity' => '32,392', 'manager' => 'Luis Miguel Ramis', 'founded_year' => 1949],
            ['league_slug' => 'serie-a', 'name' => 'Lazio', 'full_name' => 'SS Lazio', 'slug' => 'lazio', 'crest_code' => 'laz', 'color_hex' => '#87CEEB', 'stadium' => 'Stadio Olimpico', 'stadium_capacity' => '70,634', 'manager' => 'Maurizio Sarri', 'founded_year' => 1900],
            ['league_slug' => 'ligue-1', 'name' => 'Le Havre', 'full_name' => 'Le Havre AC', 'slug' => 'le-havre-ac', 'crest_code' => 'leh', 'color_hex' => '#002F6C', 'stadium' => 'Stade Oceane', 'stadium_capacity' => '25,178', 'manager' => 'Didier Digard', 'founded_year' => 1872],
            ['league_slug' => 'serie-a', 'name' => 'Lecce', 'full_name' => 'US Lecce', 'slug' => 'lecce', 'crest_code' => 'lec', 'color_hex' => '#FFD700', 'stadium' => 'Stadio Via del Mare', 'stadium_capacity' => '31,533', 'manager' => 'Marco Giampaolo', 'founded_year' => 1908],
            ['league_slug' => 'premier-league', 'name' => 'Leeds United', 'full_name' => 'Leeds United FC', 'slug' => 'leeds-united', 'crest_code' => 'lee', 'color_hex' => '#1D428A', 'stadium' => 'Elland Road', 'stadium_capacity' => '37,890', 'manager' => 'Daniel Farke', 'founded_year' => 1919],
            ['league_slug' => 'la-liga', 'name' => 'Leganes', 'full_name' => 'CD Leganes', 'slug' => 'leganes', 'crest_code' => 'leg', 'color_hex' => '#003DA5', 'stadium' => 'Estadio Municipal de Butarque', 'stadium_capacity' => '12,450', 'manager' => 'Borja Jimenez', 'founded_year' => 1928],
            ['league_slug' => 'premier-league', 'name' => 'Liverpool', 'full_name' => 'Liverpool FC', 'slug' => 'liverpool', 'crest_code' => 'liv', 'color_hex' => '#C8102E', 'stadium' => 'Anfield', 'stadium_capacity' => '61,000', 'manager' => 'Arne Slot', 'founded_year' => 1892],
            ['league_slug' => 'ligue-1', 'name' => 'Lille', 'full_name' => 'Lille OSC', 'slug' => 'losc-lille', 'crest_code' => 'lil', 'color_hex' => '#E2001A', 'stadium' => 'Stade Pierre-Mauroy', 'stadium_capacity' => '50,186', 'manager' => 'Bruno Genesio', 'founded_year' => 1944],
            ['league_slug' => 'bundesliga', 'name' => 'Mainz 05', 'full_name' => '1. FSV Mainz 05', 'slug' => 'mainz-05', 'crest_code' => 'm05', 'color_hex' => '#C10E21', 'stadium' => 'Mewa Arena', 'stadium_capacity' => '33,305', 'manager' => 'Bo Henriksen', 'founded_year' => 1905],
            ['league_slug' => 'la-liga', 'name' => 'Mallorca', 'full_name' => 'RCD Mallorca', 'slug' => 'mallorca', 'crest_code' => 'mll', 'color_hex' => '#CC0000', 'stadium' => 'Visit Mallorca Estadi', 'stadium_capacity' => '23,142', 'manager' => 'Jagoba Arrasate', 'founded_year' => 1916],
            ['league_slug' => 'premier-league', 'name' => 'Man City', 'full_name' => 'Manchester City FC', 'slug' => 'manchester-city', 'crest_code' => 'mci', 'color_hex' => '#6CABDD', 'stadium' => 'Etihad Stadium', 'stadium_capacity' => '53,400', 'manager' => 'Pep Guardiola', 'founded_year' => 1880],
            ['league_slug' => 'premier-league', 'name' => 'Man United', 'full_name' => 'Manchester United FC', 'slug' => 'manchester-united', 'crest_code' => 'mun', 'color_hex' => '#DA291C', 'stadium' => 'Old Trafford', 'stadium_capacity' => '74,197', 'manager' => 'Ruben Amorim', 'founded_year' => 1878],
            ['league_slug' => 'ligue-1', 'name' => 'Montpellier', 'full_name' => 'Montpellier Herault SC', 'slug' => 'montpellier-hsc', 'crest_code' => 'mhs', 'color_hex' => '#003DA5', 'stadium' => 'Stade de la Mosson', 'stadium_capacity' => '32,900', 'manager' => 'Jean-Louis Gasset', 'founded_year' => 1919],
            ['league_slug' => 'serie-a', 'name' => 'Napoli', 'full_name' => 'SSC Napoli', 'slug' => 'napoli', 'crest_code' => 'nap', 'color_hex' => '#12A0D7', 'stadium' => 'Stadio Diego Armando Maradona', 'stadium_capacity' => '54,726', 'manager' => 'Antonio Conte', 'founded_year' => 1926],
            ['league_slug' => 'premier-league', 'name' => 'Newcastle', 'full_name' => 'Newcastle United FC', 'slug' => 'newcastle-united', 'crest_code' => 'new', 'color_hex' => '#241F20', 'stadium' => 'St James\' Park', 'stadium_capacity' => '52,258', 'manager' => 'Eddie Howe', 'founded_year' => 1892],
            ['league_slug' => 'premier-league', 'name' => 'Nottingham Forest', 'full_name' => 'Nottingham Forest FC', 'slug' => 'nottingham-forest', 'crest_code' => 'nfo', 'color_hex' => '#DD0000', 'stadium' => 'City Ground', 'stadium_capacity' => '30,445', 'manager' => 'Sean Dyche', 'founded_year' => 1865],
            ['league_slug' => 'ligue-1', 'name' => 'Nice', 'full_name' => 'OGC Nice', 'slug' => 'ogc-nice', 'crest_code' => 'nic', 'color_hex' => '#ED1B34', 'stadium' => 'Allianz Riviera', 'stadium_capacity' => '36,178', 'manager' => 'Franck Haise', 'founded_year' => 1904],
            ['league_slug' => 'ligue-1', 'name' => 'Marseille', 'full_name' => 'Olympique de Marseille', 'slug' => 'olympique-de-marseille', 'crest_code' => 'om', 'color_hex' => '#00AFF0', 'stadium' => 'Orange Velodrome', 'stadium_capacity' => '67,394', 'manager' => 'Roberto De Zerbi', 'founded_year' => 1899],
            ['league_slug' => 'ligue-1', 'name' => 'Lyon', 'full_name' => 'Olympique Lyonnais', 'slug' => 'olympique-lyonnais', 'crest_code' => 'ol', 'color_hex' => '#0F3B82', 'stadium' => 'Groupama Stadium', 'stadium_capacity' => '59,186', 'manager' => 'Paulo Fonseca', 'founded_year' => 1950],
            ['league_slug' => 'la-liga', 'name' => 'Osasuna', 'full_name' => 'Club Atletico Osasuna', 'slug' => 'osasuna', 'crest_code' => 'osa', 'color_hex' => '#D2001C', 'stadium' => 'El Sadar', 'stadium_capacity' => '23,576', 'manager' => 'Vicente Moreno', 'founded_year' => 1920],
            ['league_slug' => 'ligue-1', 'name' => 'Paris SG', 'full_name' => 'Paris Saint-Germain FC', 'slug' => 'paris-saint-germain', 'crest_code' => 'psg', 'color_hex' => '#004170', 'stadium' => 'Parc des Princes', 'stadium_capacity' => '47,929', 'manager' => 'Luis Enrique', 'founded_year' => 1970],
            ['league_slug' => 'serie-a', 'name' => 'Parma', 'full_name' => 'Parma Calcio 1913', 'slug' => 'parma', 'crest_code' => 'par', 'color_hex' => '#001489', 'stadium' => 'Stadio Ennio Tardini', 'stadium_capacity' => '22,352', 'manager' => 'Fabio Pecchia', 'founded_year' => 1913],
            ['league_slug' => 'la-liga', 'name' => 'Rayo Vallecano', 'full_name' => 'Rayo Vallecano de Madrid', 'slug' => 'rayo-vallecano', 'crest_code' => 'ray', 'color_hex' => '#E30613', 'stadium' => 'Campo de Futbol de Vallecas', 'stadium_capacity' => '14,708', 'manager' => 'Inigo Perez', 'founded_year' => 1924],
            ['league_slug' => 'bundesliga', 'name' => 'RB Leipzig', 'full_name' => 'RB Leipzig', 'slug' => 'rb-leipzig', 'crest_code' => 'rbl', 'color_hex' => '#DD0741', 'stadium' => 'Red Bull Arena', 'stadium_capacity' => '47,069', 'manager' => 'Ole Werner', 'founded_year' => 2009],
            ['league_slug' => 'ligue-1', 'name' => 'Lens', 'full_name' => 'Racing Club de Lens', 'slug' => 'rc-lens', 'crest_code' => 'rcl', 'color_hex' => '#ED1C24', 'stadium' => 'Stade Bollaert-Delelis', 'stadium_capacity' => '38,223', 'manager' => 'Will Still', 'founded_year' => 1906],
            ['league_slug' => 'ligue-1', 'name' => 'Strasbourg', 'full_name' => 'RC Strasbourg Alsace', 'slug' => 'rc-strasbourg', 'crest_code' => 'str', 'color_hex' => '#0033A0', 'stadium' => 'Stade de la Meinau', 'stadium_capacity' => '26,109', 'manager' => 'Liam Rosenior', 'founded_year' => 1906],
            ['league_slug' => 'la-liga', 'name' => 'Real Betis', 'full_name' => 'Real Betis Balompie', 'slug' => 'real-betis', 'crest_code' => 'bet', 'color_hex' => '#00954C', 'stadium' => 'Estadio Benito Villamarin', 'stadium_capacity' => '60,720', 'manager' => 'Manuel Pellegrini', 'founded_year' => 1907],
            ['league_slug' => 'la-liga', 'name' => 'Real Madrid', 'full_name' => 'Real Madrid CF', 'slug' => 'real-madrid', 'crest_code' => 'rma', 'color_hex' => '#00529F', 'stadium' => 'Santiago Bernabeu', 'stadium_capacity' => '78,297', 'manager' => 'Xabi Alonso', 'founded_year' => 1902],
            ['league_slug' => 'la-liga', 'name' => 'Real Sociedad', 'full_name' => 'Real Sociedad de Futbol', 'slug' => 'real-sociedad', 'crest_code' => 'rso', 'color_hex' => '#0067B1', 'stadium' => 'Reale Arena', 'stadium_capacity' => '39,313', 'manager' => 'Sergio Francisco', 'founded_year' => 1909],
            ['league_slug' => 'la-liga', 'name' => 'Valladolid', 'full_name' => 'Real Valladolid CF', 'slug' => 'real-valladolid', 'crest_code' => 'vll', 'color_hex' => '#6C2C91', 'stadium' => 'Estadio Jose Zorrilla', 'stadium_capacity' => '26,512', 'manager' => 'Guillermo Almada', 'founded_year' => 1928],
            ['league_slug' => 'serie-a', 'name' => 'Sassuolo', 'full_name' => 'US Sassuolo Calcio', 'slug' => 'sassuolo', 'crest_code' => 'sas', 'color_hex' => '#00A650', 'stadium' => 'Mapei Stadium', 'stadium_capacity' => '21,584', 'manager' => 'Fabio Grosso', 'founded_year' => 1920],
            ['league_slug' => 'bundesliga', 'name' => 'Freiburg', 'full_name' => 'SC Freiburg', 'slug' => 'sc-freiburg', 'crest_code' => 'scf', 'color_hex' => '#E2231A', 'stadium' => 'Europa-Park Stadion', 'stadium_capacity' => '34,700', 'manager' => 'Julian Schuster', 'founded_year' => 1904],
            ['league_slug' => 'la-liga', 'name' => 'Sevilla', 'full_name' => 'Sevilla FC', 'slug' => 'sevilla', 'crest_code' => 'sev', 'color_hex' => '#D2001C', 'stadium' => 'Ramon Sanchez Pizjuan', 'stadium_capacity' => '43,883', 'manager' => 'Matias Almeyda', 'founded_year' => 1890],
            ['league_slug' => 'ligue-1', 'name' => 'Brest', 'full_name' => 'Stade Brestois 29', 'slug' => 'stade-brestois', 'crest_code' => 'bre2', 'color_hex' => '#E2001A', 'stadium' => 'Stade Francis-Le Ble', 'stadium_capacity' => '15,220', 'manager' => 'Eric Roy', 'founded_year' => 1950],
            ['league_slug' => 'ligue-1', 'name' => 'Reims', 'full_name' => 'Stade de Reims', 'slug' => 'stade-de-reims', 'crest_code' => 'sdr', 'color_hex' => '#E2001A', 'stadium' => 'Stade Auguste-Delaune', 'stadium_capacity' => '21,684', 'manager' => 'Luka Elsner', 'founded_year' => 1931],
            ['league_slug' => 'ligue-1', 'name' => 'Rennes', 'full_name' => 'Stade Rennais FC', 'slug' => 'stade-rennais', 'crest_code' => 'ren', 'color_hex' => '#ED1C24', 'stadium' => 'Roazhon Park', 'stadium_capacity' => '29,778', 'manager' => 'Habib Beye', 'founded_year' => 1901],
            ['league_slug' => 'premier-league', 'name' => 'Sunderland', 'full_name' => 'Sunderland AFC', 'slug' => 'sunderland', 'crest_code' => 'sun', 'color_hex' => '#EB172B', 'stadium' => 'Stadium of Light', 'stadium_capacity' => '48,707', 'manager' => 'Regis Le Bris', 'founded_year' => 1879],
            ['league_slug' => 'serie-a', 'name' => 'Torino', 'full_name' => 'Torino FC', 'slug' => 'torino', 'crest_code' => 'tor', 'color_hex' => '#7B1E3A', 'stadium' => 'Stadio Olimpico Grande Torino', 'stadium_capacity' => '27,958', 'manager' => 'Paolo Vanoli', 'founded_year' => 1906],
            ['league_slug' => 'premier-league', 'name' => 'Tottenham', 'full_name' => 'Tottenham Hotspur FC', 'slug' => 'tottenham-hotspur', 'crest_code' => 'tot', 'color_hex' => '#132257', 'stadium' => 'Tottenham Hotspur Stadium', 'stadium_capacity' => '62,850', 'manager' => 'Thomas Frank', 'founded_year' => 1882],
            ['league_slug' => 'ligue-1', 'name' => 'Toulouse', 'full_name' => 'Toulouse FC', 'slug' => 'toulouse-fc', 'crest_code' => 'tfc', 'color_hex' => '#6A0DAD', 'stadium' => 'Stadium de Toulouse', 'stadium_capacity' => '33,150', 'manager' => 'Carles Martinez Novell', 'founded_year' => 1970],
            ['league_slug' => 'bundesliga', 'name' => 'Hoffenheim', 'full_name' => 'TSG 1899 Hoffenheim', 'slug' => 'tsg-hoffenheim', 'crest_code' => 'tsg', 'color_hex' => '#1961B5', 'stadium' => 'PreZero Arena', 'stadium_capacity' => '30,150', 'manager' => 'Christian Ilzer', 'founded_year' => 1899],
            ['league_slug' => 'serie-a', 'name' => 'Udinese', 'full_name' => 'Udinese Calcio', 'slug' => 'udinese', 'crest_code' => 'udi', 'color_hex' => '#000000', 'stadium' => 'Bluenergy Stadium', 'stadium_capacity' => '25,144', 'manager' => 'Kosta Runjaic', 'founded_year' => 1896],
            ['league_slug' => 'bundesliga', 'name' => 'Union Berlin', 'full_name' => '1. FC Union Berlin', 'slug' => 'union-berlin', 'crest_code' => 'fcu', 'color_hex' => '#EB1923', 'stadium' => 'Stadion An der Alten Forsterei', 'stadium_capacity' => '22,012', 'manager' => 'Steffen Baumgart', 'founded_year' => 1966],
            ['league_slug' => 'la-liga', 'name' => 'Valencia', 'full_name' => 'Valencia CF', 'slug' => 'valencia', 'crest_code' => 'val', 'color_hex' => '#FF7900', 'stadium' => 'Mestalla', 'stadium_capacity' => '49,430', 'manager' => 'Carlos Corberan', 'founded_year' => 1919],
            ['league_slug' => 'serie-a', 'name' => 'Venezia', 'full_name' => 'Venezia FC', 'slug' => 'venezia', 'crest_code' => 'ven', 'color_hex' => '#FF6600', 'stadium' => 'Stadio Pier Luigi Penzo', 'stadium_capacity' => '11,150', 'manager' => 'Eusebio Di Francesco', 'founded_year' => 1907],
            ['league_slug' => 'bundesliga', 'name' => 'VfB Stuttgart', 'full_name' => 'VfB Stuttgart', 'slug' => 'vfb-stuttgart', 'crest_code' => 'vfb', 'color_hex' => '#E32219', 'stadium' => 'MHPArena', 'stadium_capacity' => '60,449', 'manager' => 'Sebastian Hoeness', 'founded_year' => 1893],
            ['league_slug' => 'bundesliga', 'name' => 'Bochum', 'full_name' => 'VfL Bochum 1848', 'slug' => 'vfl-bochum', 'crest_code' => 'boc', 'color_hex' => '#005CA9', 'stadium' => 'Vonovia Ruhrstadion', 'stadium_capacity' => '26,000', 'manager' => 'Dieter Hecking', 'founded_year' => 1848],
            ['league_slug' => 'bundesliga', 'name' => 'Wolfsburg', 'full_name' => 'VfL Wolfsburg', 'slug' => 'vfl-wolfsburg', 'crest_code' => 'wob', 'color_hex' => '#65B32E', 'stadium' => 'Volkswagen Arena', 'stadium_capacity' => '30,000', 'manager' => 'Paul Simonis', 'founded_year' => 1945],
            ['league_slug' => 'la-liga', 'name' => 'Villarreal', 'full_name' => 'Villarreal CF', 'slug' => 'villarreal', 'crest_code' => 'vil', 'color_hex' => '#FFD200', 'stadium' => 'Estadio de la Ceramica', 'stadium_capacity' => '23,500', 'manager' => 'Marcelino Garcia Toral', 'founded_year' => 1923],
            ['league_slug' => 'bundesliga', 'name' => 'Werder Bremen', 'full_name' => 'SV Werder Bremen', 'slug' => 'werder-bremen', 'crest_code' => 'svw', 'color_hex' => '#1D9053', 'stadium' => 'Weserstadion', 'stadium_capacity' => '42,100', 'manager' => 'Horst Steffen', 'founded_year' => 1899],
            ['league_slug' => 'premier-league', 'name' => 'West Ham', 'full_name' => 'West Ham United FC', 'slug' => 'west-ham-united', 'crest_code' => 'whu', 'color_hex' => '#7A263A', 'stadium' => 'London Stadium', 'stadium_capacity' => '62,500', 'manager' => 'Graham Potter', 'founded_year' => 1895],
            ['league_slug' => 'premier-league', 'name' => 'Wolves', 'full_name' => 'Wolverhampton Wanderers FC', 'slug' => 'wolverhampton-wanderers', 'crest_code' => 'wol', 'color_hex' => '#FDB913', 'stadium' => 'Molineux Stadium', 'stadium_capacity' => '31,700', 'manager' => 'Vitor Pereira', 'founded_year' => 1877],
        ];

        $leagueIds = League::pluck('id', 'slug');

        foreach ($teams as $team) {
            $leagueSlug = $team['league_slug'];
            unset($team['league_slug']);
            $team['league_id'] = $leagueIds[$leagueSlug];
            Team::updateOrCreate(['slug' => $team['slug']], $team);
        }
    }
}
